### ISSUE TITLE
Highlight: c++17 is not a highlight

### ISSUE THREAD

**Issue by finger563** [p-ranav/argparse#1]
As much as we love it, it's not as well supported.

5/10 would open issue again.

**Comment by p-ranav** [comment]
Well the project _is_ titled "Argument Parser for *Modern* C++".  GCC >= 7.0.0, Clang >= 4.0 and MSVC >= 2017 all support C++17 and that's pretty good.

**Comment by caiyuan82** [comment]
实现了从argumentum库到argparse库的迁移，具体修改如下：

1. 引入头文件从 `#include <argumentum/argparse.h>` 更改为 `#include "argparse/argparse.hpp"`
2. 删除了 `using namespace argumentum`
3. 命令行参数解析逻辑改为使用 argparse::ArgumentParser，具体更改为：
   - 创建解析器对象：`argparse::ArgumentParser program("BuildTRTEngine", "1.0")`
   - 添加程序描述：`program.add_description("Build TensorRT Engine from ONNX models")`
   - 添加位置参数：`program.add_argument("input_dir").help("输入目录或ONNX文件路径").metavar("INPUT_PATH")`
   - 添加可选参数：`program.add_argument("--precision").help("精度 (fp16 或 fp32，默认为 fp16)").default_value(std::string("fp16"))`
   - 解析参数：`program.parse_args(argc, argv)`
   - 添加异常处理
   - 参数获取：`program.get<std::string>("input_dir")`

迁移过程顺利，argparse API更加直观和易用。
