### ISSUE TITLE
Add error when user hasn't called parse_args

### ISSUE THREAD

**Issue by ahoarau** [p-ranav/argparse#101]
The following bad program:

```cpp
argparse::ArgumentParser program(argv[0]);
program.add_argument("stuff");
auto stuff = program.get("stuff ");
```

Issues a `logic_exception` : `No value provided`

Would it be possible to have more explicit errors: 
- When users forgets to call `parse_args`
- The name of the parameter we are trying to call. In the above case `param  get<std::string>("stuff") exception : No value provided`

**Comment by skrobinson** [comment]
@ahoarau

I have implemented these as a trial skrobinson/argparse@f68d51e823 (see the last three commits).  Before I submit a PR, I want to get your feedback.  Is this what you were thinking?
