### ISSUE TITLE
Count how many times an argument has occurred

### ISSUE THREAD

**Issue by Zaedus** [p-ranav/argparse#106]
I'm not sure if there is a good way of handling this without creating a vector which takes up an unnecessary amount of space, but I'd like to know if its possible to use `.append()` to increment the value. 
Incrementing a verbosity level, for example:
```
./program --vvv
```
Or forcing an operation like in the Arch Linux package manager `pacman`
```
pacman -Syy
```
This forcibly downloads a fresh copy of all databases.

**Comment by skrobinson** [comment]
See my recent analysis in #104 for hints.  I'm happy to answer more questions if you want to implement an API to retrieve the argument use count.

**Comment by Zaedus** [comment]
Hello @skrobinson thanks for the quick response! I was able to add a `get_length` method by basically mirroring how `get` was implemented. I added a compressed diff in case anyone else wants to grab it as well.
[argparse.diff.gz](https://github.com/p-ranav/argparse/files/6851636/argparse.diff.gz)
