### ISSUE TITLE
Argparse should not call `exit()`

### ISSUE THREAD

**Issue by KOLANICH** [p-ranav/argparse#112]
Instead it should return control and provide the information about what had happenned in a structured way.

**Comment by skrobinson** [comment]
`std::exit` is only called if the default *--help* or *--version* arguments are used.  If you need to return from parsing these options in your program, could you override *-h* and *--help*? (See "Users can override the help options" in `test/test_help.cpp`.)

Exiting after *--help* seems standard among argument parsing libraries across several languages.  Having used a similar library in another language, I expect this behavior and
rely on argparse to exit my command line program when *--help* is given.

**Comment by KOLANICH** [comment]
>`std::exit` is only called if the default --help or --version arguments are used.

I mean exactly this.

>Exiting after --help seems standard among argument parsing libraries across several languages. Having used a similar library in another language, I expect this behavior and
rely on argparse to exit my command line program when --help is given.

In C++ only few libraries I saw do this. Most of them throw an exception a user must catch in `main` and then do `std::cout << arg_parsing_lib_object << std::endl; return 0;`

> If you need to return from parsing these options in your program, could you override -h and --help? (See "Users can override the help options" in test/test_help.cpp.)

Thanks for the info, I will try and report if this would work as needed. Though IMHO it is a bit dirty to redefine such options.

**Comment by skrobinson** [comment]
> Most of them throw an exception a user must catch

Which, IMHO, is not the better choice.  `--help` or `--version` on the command line are not errors.

> Though IMHO it is a bit dirty to redefine such options.

I initially agreed, but now I look at redefining the two default arguments as another way to customize an ArgumentParser instance for a specific use.

**Comment by KOLANICH** [comment]
Thanks for the info, that works.

**Comment by trick2011** [comment]
It might be normal behavior to stop the program after calling `-h` and `-v` but calling `std::exit` is a very important problem, it [breaks RAII](https://en.cppreference.com/w/cpp/utility/program/exit#:~:text=Stack%20is%20not%20unwound%3A%20destructors%20of%20variables%20with%20automatic%20storage%20duration%20are%20not%20called.)! 

It is not acceptable that a library breaks RAII without even mentioning that it is one of the possible execution paths!

In the normal flow we are already catching exceptions that might happen during parsing, adding a normal program termination exception wouldn't add much code and gives clear intended behavior and is better in terms of RAII.

**Comment by wanjiadenghuo111** [comment]
亲，来信已经收到！祝你快乐！

**Comment by marzer** [comment]
> I agree - a library should never call exit because that will interrupt the program no matter what.

Indeed, I argued as much in https://github.com/p-ranav/argparse/pull/251.

**Comment by thedayofcondor** [comment]
Overriding the action for `-v` and `--help` seems to work - however I am using a lot of sub-parsers, and it looks like it has to be overridden in each subparser

**Comment by trick2011** [comment]
> Overriding the action for `-v` and `--help` seems to work - however I am using a lot of sub-parsers, and it looks like it has to be overridden in each subparser

Good to know, but it's a hack around a flawed part of the design.

Either way, this issue is closed so unless someone wants to reopen it or create a new pull request. ¯\_(ツ)_/¯
