### ISSUE TITLE
Argparse should not output messages into `std::cout` directly

### ISSUE THREAD

**Issue by KOLANICH** [p-ranav/argparse#113]
Instead it should allow library user to output them in the preferred way.

**Comment by skrobinson** [comment]
`std::cout` is only used for help/version output before exiting.  This is what I expect to happen, since I am asking argparse to take over handling command line options for me.

Two options for you are to override these two arguments or temporarily capture `std::cout`.  I've successfully used `std::cout` capturing for unit tests in a project using argparse.

**Comment by KOLANICH** [comment]
>`std::cout` is only used for help/version output before exiting. This is what I expect to happen, since I am asking argparse to take over handling command line options for me.

I have a bit different use case. I have created an abstraction layer (not yet published it though) around > 10 libs for parsing CLI args unifying their API. It was decided that the most flexible way is to allow a user to provide a stream (most of libs require a user to manually `std::cout << parser_object << std::endl;` in the case of help message) into which error messages from libs would be output. I.e. I can imagine a network service which uses a CLI parsing lib, but instead of printing into stdout prints into an `std::stringstream` and then sends the results to a user. And redefining global objects is clearly not thread-safe.

**Comment by skrobinson** [comment]
> I.e. I can imagine a network service which uses a CLI parsing lib, but instead of printing into stdout prints into an `std::stringstream` and then sends the results to a user.

This is a clever idea.  But, I have a hard time seeing the utilty of `--help` output displaying at a distance from the CLI invocation.  I can see a use for `--version` output to remote logging.  Output from other parameters is left to the developer.

Even though I'm skeptical of the need, this should be possible in a backward-compatible way.  Replace current `std::cout` use with a `std::ostream`, injectable at ArgumentParser construction.  The default output stream would be `std::cout`, but it could be replaced with another stream object.

Does this seem feasible to you?

>> temporarily capture `std::cout`

> And redefining global objects is clearly not thread-safe.

Now that I better understand your use, I agree this is not the right choice for you.

**Comment by KOLANICH** [comment]
>Does this seem feasible to you?

Yes, it seems to be feasible for me to provide the strams at construction. Even better can be done by making the fields storing the streams public (or keep them private and provide accessors, but IMHO accessors not always make sense).

**Comment by skrobinson** [comment]
> currently the lib uses hardcoded streams.

But the hardcoded `std::cout` are only used with the default `--help` and `--version`.  Overriding these arguments replaces the `Argument` objects associated with these keys so the test before using `std::cout` becomes false.

**Comment by KOLANICH** [comment]
Yeah, I currently solved this problem this way. (Though the hardcoded stuff doesn't feel right.)
