### ISSUE TITLE
argparse should convert values itself, not to rely on user-supplied functions

### ISSUE THREAD

**Issue by KOLANICH** [p-ranav/argparse#114]
at least for such types as `int` and `double`

**Comment by skrobinson** [comment]
How would these types be determined?

I'm open to this idea, but I thought the reason for the `.action` lambda was to safely convert from a `std::string` to the user's needed type.

**Comment by KOLANICH** [comment]
>How would these types be determined?

In other libs there are 2 approaches.

1. C++ libraries usually rely on templates. Usually

* a template in the place of assigning a variable from the option, if the option stores the parsed value. It has a drawback of having an error in the place the value is got.

or

* a template in the place of declaring the option, if an option stores a pointer/reference to the place it should store the value. This is preferred since it allows specifying the type of arg, verifying it assignment in compile time and generating help properly. Also it is the easiest case for me to integrate into the backend (given that all the required features are implemented in the lib itself, if it is not, it becomes the hardest case of integration), since it usually require only a single assignment in `_addArg` method of the backend class.

* ones requiring templates in both places. It usually combines drawbacks and costs of both approaches and also relies on type erasure containers and RTTI, so IDK why it is was chosen.

2. More correctly also use not only templates, but also inheritance, to allow generic processing of options. Some libs inherit templates from a common abstract class. Some C libs also mock inheritance by having a common header.

3. C libs and C++ libs based on C ones or C++ libs mimicking the interface of well-known C libs like GNU getopt, store a value in the struct. `dropt` stores a pointer to a function assigning a value.

I also have a very rudimentary lib doing fallback parsing of values from strings depending on the value of a enum, in the case the underlying library doesn't support conversion, i.e. I currently apply it to your lib, if you want, you can reuse its code, once I publish it.

**Comment by skrobinson** [comment]
I think the `Argument::scan<Shape, T>` function may already do what you
want.  `scan` is not documented, so it's easy to miss.  But there are extensive test cases in `test/test_scan.cpp`.  Could you take a look and report back if this meets your needs?

**Comment by KOLANICH** [comment]
Thanks, that works!
