### ISSUE TITLE
Allow `scan` determine base of ints in runtime using common prefixes 0x, 0b and 0o

### ISSUE THREAD

**Issue by KOLANICH** [p-ranav/argparse#116]

**Comment by skrobinson** [comment]
I think most of this is handled, see the `parse_number<T, Param>` struct.

A leading `0x` or `0X` cause input to be treated as a hex value.  A leading `0` prompts octal conversion (versus Python's `0o`).

Yes, I do not see support for `0b`.  Anyone interested in adding `0b` support could copy and adapt the hex prefix support.
