### ISSUE TITLE
Vector of any length as argument

### ISSUE THREAD

**Issue by DavidAce** [p-ranav/argparse#118]
I wonder if argparse supports dynamic-length vector as arguments. Something like

1.  `./app --try-values 3.312 7.53 -71.2 ...`

where the number of values is unknown at compile-time (i.e. without `.nargs(#)`).
I've been looking at the readme and other issues here, but all I can find is support for repeated arguments. If I understand correctly, this should work:

2. `./app --try-values 3.312  --try-values 7.53  --try-values -71.2 ...`

but this can quickly become tedious.

Is there a way to achieve version 1? It would be nice to do this with `.nargs(-1)` or `.nargs(0)` or an enum overload like `.nargs(narg::dynamic)`.

**Comment by p-ranav** [comment]
argparse supports gathering remaining args. See [here](file:///android_asset/md/#gathering-remaining-arguments). Hope this helps.

**Comment by p-ranav** [comment]
argparse provides support for gathering remaining args. See here: https://github.com/p-ranav/argparse#gathering-remaining-arguments. Hope this helps.

**Comment by DavidAce** [comment]
Thanks! I think I can see how that solves the issue for a single vector, but I was really hoping to pass multiple vectors. Consider for instance

`./app --rows=8,16,32 ... --columns=2,4,6... `

If this is not possible now, is this something you would consider in a future version or in a pull request?

**Comment by p-ranav** [comment]
@DavidAce There's a [new release](https://github.com/p-ranav/argparse/releases/tag/v2.6) of argparse that will support this feature request. Hope this helps. 

Regards,
