### ISSUE TITLE
conan package 2.1 does not match 2.1 tag

### ISSUE THREAD

**Issue by kobi-ca** [p-ranav/argparse#126]
related to my comment here:
https://github.com/p-ranav/argparse/issues/2
conan package https://conan.io/center/argparse
does not match:
https://github.com/p-ranav/argparse/tree/v2.1
for example, it does not have "scan" function. 
anything that I am missing?
I basically cannot do something very simple as:
```cpp
    program.add_argument("--something")
        .default_value(0);
```
if I pass --something 10 in the cmd line arg, I'm getting bad cast when trying to interpret it as int:
```cpp
program.get<int>("--something");
```
It is as if I need to have all std::any be strings and then manually convert it to ints.
I need something like boost which has the `.as<T>()`

Any pointers are appreciated. thanks

**Comment by skrobinson** [comment]
@p-ranav

Did you mean to move the v2.1 tag from commit 473d550 to commit b0cb28a?

**Comment by kobi-ca** [comment]
@skrobinson  - the tag is applied on the right tag, right? or am I missing here something?

**Comment by skrobinson** [comment]
Between Nov. 22, 2019, and Sept. 1, 2021, the v2.1 tag pointed at a different commit than it now does.

**Comment by p-ranav** [comment]
I didn't mean to make any moves? This is odd. 

Maybe I'm mistaken or forgetting something:
* v2.0 was released in Nov 21 2019. 
* 12 days ago, I released v2.1 here on GitHub for the first time after many requests.

**Comment by p-ranav** [comment]
My bad, I just discovered the tag v2.1 was created in December 2019: https://github.com/p-ranav/argparse/issues/70

**Comment by kobi-ca** [comment]
so just for me to understand. the 2.1 uploaded archive was from dec 2019 but the v2.1 later on moved?

**Comment by kobi-ca** [comment]
question is how conan folks can avoid such accident in the future? is there such a mechanism?

**Comment by skrobinson** [comment]
Does Conan install from an uploaded archive or dynamically pull from auxiliary project repositories (APR) such as argparse? If Conan uses an uploaded archive, I would not expect any problems with tag changes. But if Conan is using tags in APRs to pin a versoin for install, changing a tag could break builds using Conan.

I'm hoping @p-ranav will re-tag commit 473d550 as v2.1 and add a new tag for commit b0cb28a.

**Comment by kobi-ca** [comment]
I still dont understand how this happened. the conan-index yaml has the url of the correct archive. If you wget it, you'll obtain a package named v2.1 which matches the v2.1 tag. but somehow there is another package (with v2.1?) somewhere (where??) that is _actually_ pulled in during conan install. and this is the 2019(?) one. 
I dont understand how conan index yaml points to the right tgz but conan install cmd brings a different one. this is a major issue in the current conan mechanism IMO unless I'm missing here something.

**Comment by p-ranav** [comment]
Okay. 

* v2.1 now points to 473d550
* v2.2 is the latest release, points to b0cb28a

**Comment by kobi-ca** [comment]
is there anything we need to do to get the conan index updated ?

**Comment by Croydon** [comment]
> 
> 
> I still dont understand how this happened. the conan-index yaml has the url of the correct archive. If you wget it, you'll obtain a package named v2.1 which matches the v2.1 tag. but somehow there is another package (with v2.1?) somewhere (where??) that is _actually_ pulled in during conan install. and this is the 2019(?) one.
> I dont understand how conan index yaml points to the right tgz but conan install cmd brings a different one. this is a major issue in the current conan mechanism IMO unless I'm missing here something.

If you are installing pre-build Conan packages with `conan install` you get the source / libs etc. from the day it was built even when the tag was re-tagged in the meantime. This is not a Conan issue. Git Tags / Releases shouldn't be re-released with changes.

The v2.1 tag seems to be restored now to its former commit, so everything should be fine now

**Comment by kobi-ca** [comment]
I see. so when it was built/tagged in the past, conan is keeping this snapshot. So what is this yaml that points to the 2.1 archive?
It's confusing since this yaml points to URL that has the correct data but conan install is probably taking the data from some other location.

Anyway - so what is left right now to have 2.2 shows up in conan-center?

**Comment by Croydon** [comment]
> I see. so when it was built/tagged in the past, conan is keeping this snapshot. So what is this yaml that points to the 2.1 archive?
It's confusing since this yaml points to URL that has the correct data but conan install is probably taking the data from some other location.

Conan leaves you the choice if you download prebuilt packages or if you build from source. If you download the packages you have a snapshot in time, if you build from source Conan is downloading from the URLs in the `conandata.yml` file and checks them with a sha256 checksum, hence catching changed downloads (mostly a security consideration).

> Anyway - so what is left right now to have 2.2 shows up in conan-center?

Anyone can open PRs to the Conan Center Index and adding new recipes and/or versions.
