### ISSUE TITLE
A question about program name location in the help message

### ISSUE THREAD

**Issue by blueskyson** [p-ranav/argparse#135]
If I initialize a parser by:
```
argparse::ArgumentParser program("My Program");
``` 
and run `my_program -h`, then a terminal will display:
```
Usage: My Program [options] 

Optional arguments:
...
```

The string "My Program" is mixed with usage, is this on purpose? 

I have such question because every help message I've seen looks like:
```
My Program
Usage: [options] 

...
```
or
```
Usage:  [options]

My Program

...
```

**Comment by p-ranav** [comment]
Yes, this is designed to be similar to python's `argparse` behavior:

```console
$ python myprogram.py --help
usage: myprogram.py [-h] [--foo FOO]

optional arguments:
 -h, --help  show this help message and exit
 --foo FOO   foo help
```

The program name is meant to be the name of the binary or app that one would end up running after everything is built.

So something like this:

```console
Usage: my_app [options] 

Optional arguments:
...
```
