### ISSUE TITLE
Compilation error g++

### ISSUE THREAD

**Issue by x1mus** [p-ranav/argparse#137]
Hi,

I'm currently trying to include this parser in a small project I have but I can't figure out how to make it work.
As soon as I include it (without even doing anything else), this generates an error.

My code is litterally empty. Empty main function + the include and the compilation crashs (maybe I'm doing it wrong ?)
```c++
#include "argparse.hpp"

int main(int argc, char **argv) {
	
	return 0;
}
```

Here's a [pastebin](https://pastebin.com/F8iSY6CC) to the entire error message .

I'm using g++ compiler version 9.3.0 on an Ubuntu 20.04

**Comment by p-ranav** [comment]
`argparse` requires C++17. 

Those errors indicate this:

> argparse.hpp:90:6: warning: ‘if constexpr’ only available with ‘-std=c++17’ or ‘-std=gnu++17’

Maybe you are compiling for C++11 or C++14?

If you're using `g++`, the command would be something like:

```bash
g++ -std=c++17 -o app main.cpp
```

**Comment by x1mus** [comment]
Well, It was the problem, thanks for the answer !
