### ISSUE TITLE
Use .action() with int/float arguments

### ISSUE THREAD

**Issue by anderdnavarro** [p-ranav/argparse#149]
Hello!

I am very new to programming in c++ so at first I don't know if I'm doing something wrong. But, I am trying to check whether an argument meets certain parameters and I can't manage to do it with the `action()` option.

For example, this works fine:
```
program.add_argument("-w, --workDir")
.help("Main directory")
.default_value("/home")
.action([](const std::string& value) {
	if (!(fs::exists(value) & fs::is_directory(value))){
		std::cerr << "\nERROR: The directory provided does not exist\n" << std::endl;
		std::exit(1);
	} else {
		return value;
	}
});
```
However if I try to extrapolate this with numbers it doesn't work:
```
program.add_argument("--numeric_argument")
.help("Numeric example")
.scan<'g', float>()
.default_value(float(0.05))
.action([](const float& value) {
	if (value < 0.0 | value > 1.0) {
		std::cerr << "\nERROR: Numerical argument must be between 0 and 1\n" << std::endl;
	} else {
		return value;
	}
});
```
With the code above I get the following error during compilation `g++ -std=c++17 -o prueba prueba.cpp -lstdc++fs`:
```
prueba.cpp: In function ‘int main(int, char**)’:
prueba.cpp:111:4: error: no matching function for call to ‘argparse::Argument::action(main(int, char**)::<lambda(const float&)>)’
   });
    ^
In file included from prueba.cpp:1:
/usr/local/include/argparse.hpp:372:8: note: candidate: ‘template<class F, class ... Args> std::enable_if_t<is_invocable_v<F, Args ..., const std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, argparse::Argument&> argparse::Argument::action(F&&, Args&& ...)’
   auto action(F &&aAction, Args &&... aBound)
        ^~~~~~
/usr/local/include/argparse.hpp:372:8: note:   template argument deduction/substitution failed:
```

I know how to do it outside the `add_argument()` function, but is it possible to do something similar to what I have written inside the `action()` function? 

Thank you very much!
Ander

**Comment by p-ranav** [comment]
Your code has 3 issues:

1. The parameter to `.action(...)` is always a `const std::string&`. You can convert it to a float and perform the value check. 
2. For the value check, what you want is actually `(value < 0.0 || value > 1.0)`
  - In C++, `||` is the [logical OR operator](https://docs.microsoft.com/en-us/cpp/cpp/logical-or-operator-pipe-pipe?view=msvc-170), `|` is [bitwise inclusive OR operator](https://docs.microsoft.com/en-us/cpp/cpp/bitwise-inclusive-or-operator-pipe?view=msvc-170) and that is not what you want in this case.
3. In the `if` condition, you're printing with `std::cerr`. In the `else` condition, you are returning the value. 
   - In a C++ function, you should be returning the same type from all control flow paths of the function - in this case, the `if` case and the `else` case
   - You can exit from one of the control flow paths and only return a value in the other control flow path. You can do this by exiting with `std::exit()` or by throwing an exception instead (which is recommended in this case). 

```cpp
#include "argparse.hpp"

int main(int argc, char *argv[]) {

  argparse::ArgumentParser program("main");

  program.add_argument("--numeric_argument")
      .help("Numeric example")
      .scan<'g', float>()
      .default_value(float(0.05))
      .action([](const std::string &arg) {
      
        float value = std::stof(arg);
        
        if (value < 0.0 || value > 1.0) {
          throw std::runtime_error("ERROR: Numerical argument must be between 0 and 1");
        } else {
          return value;
        }
      });

  try {
    program.parse_args(argc, argv);
  } catch (const std::runtime_error &err) {
    std::cerr << err.what() << std::endl;
    std::cerr << program;
    std::exit(1);
  }
}
```

## Usage

```console
foo@bar:~$ ./main --help
Usage: main [options]

Optional arguments:
-h --help               shows help message and exits [default: false]
-v --version            prints version information and exits [default: false]
--numeric_argument      Numeric example [default: 0.05]
```

## Examples

```console
foo@bar:~$ ./main --numeric_argument 0
foo@bar:~$ ./main --numeric_argument 0.5

foo@bar:~$ ./main --numeric_argument 12
ERROR: Numerical argument must be between 0 and 1
Usage: main [options]

Optional arguments:
-h --help               shows help message and exits [default: false]
-v --version            prints version information and exits [default: false]
--numeric_argument      Numeric example [default: 0.05]
```

**Comment by anderdnavarro** [comment]
Thank you very very much!!! This has solved the problem and also I've learnt new things.

May I ask you one more question? Which is the difference between `.action([])`, `.action([=])` and `.action([&])`?

Thanks again!

**Comment by p-ranav** [comment]
Sure. 

`.action(...)` takes a lambda expression. 

In C++, a pure lambda function can have the syntax: 

```cpp
[](...) { 
  // code
}
```

## Example

The following will print `15`.

```cpp
#include <iostream>

int main() {
 
   auto add = [](auto x, auto y) { 
       return x + y;
   };

   std::cout << add(5, 10) << "\n";
}
```

A lambda expression of the above form is an "empty" lambda - it does not have access to any variables in the current scope. 

## How to use local variables?

The following would be a compile error.

```cpp
#include <iostream>

int main() {
 
   int x = 5;

   auto fn = []() { 
       std::cout << x << std::endl; // COMPILE ERROR, x is not captured
   }
}
```

To access these variables, C++ provides a few options:

### Capture by copy

You can capture a copy of the local variables by using `[=]() { ... }`

```cpp
#include <iostream>

int main() {

    int x = 5, y = 10;
 
    auto add = [=] { 
       return x + y;
    };

    x = 0;
    y = 0;

   std::cout << add() << "\n";
}
```

In the above code, a copy of `x` and `y` are bound to the lambda expression `add`. So even though `x` and `y` are set to zero later, the above code will print `15`.

### Capture by reference

Instead of copying the local variables, you can bind a reference to the local variables too:

```cpp
#include <iostream>

int main() {

    int x = 5, y = 10;
 
    auto add = [&] { 
       return x + y;
    };

    x = 0;
    y = 0;

   std::cout << add() << "\n";
}
```

Since a reference is bound, when we set `x` and `y` to zero, the result of `add` also changes. The above will print `0`.

### Capturing only some variables

You can capture or alias just some of the variables in the scope:

```cpp
#include <iostream>

int main() {

    int x = 5, y = 10;
 
    auto add_9 = [&x] {
        int y = 9;
        return x + y;
    };

   std::cout << add_9() << "\n";
}
```

The above will print `14` - Only x is used from the local scope, `y` is local to the lambda expression. 

### More on this topic

* There is a ton more to this and I've barely captured the basics. Read more [here](https://docs.microsoft.com/en-us/cpp/cpp/lambda-expressions-in-cpp?view=msvc-170).

**Comment by anderdnavarro** [comment]
Awesome! Thank you very much for your help!
