### ISSUE TITLE
Run actions with defaults values

### ISSUE THREAD

**Issue by anderdnavarro** [p-ranav/argparse#152]
Hi!

Is there any way to execute an action if the user doesn't use the argument, only with the default value. For example:

```
program.add_argument("-p")
    .help("FILE\tThis is an example")
    .default_value(std::string("ABCD"))
    .action([](const std::string& value) {
        static const std::vector<std::string> choices = { "ABCD", "EFGH" };
        if (std::find(choices.begin(), choices.end(), value) != choices.end()) {
            if ( value == "ABCD" ) {
                return std::string("/home/test/this_file.txt");
            } else {
                return std::string("/home/test/this_other_file.txt");
            }
        } 
});
```
With this example, if I run `-p ABCD` it works, but if I don't specify anything it doesn't work.

I know this can be done later, outside your function, but I think it's cleaner if I can do something like that.

Thank you very much for your help!!!
Ander

**Comment by wanjiadenghuo111** [comment]
亲，来信已经收到！祝你快乐！

**Comment by skrobinson** [comment]
I see your point and agree that it can be useful to run an action function with the `.default_value`. But I do not see a simple way to add this feature.

An alternative that would seem to fit your use case is to repeat the `.default_value` as the lambda's default return value.  See ["Restricting the set of values for an argument"](https://github.com/p-ranav/argparse#restricting-the-set-of-values-for-an-argument) for an example.

**Comment by anderdnavarro** [comment]
Thank you!!!!
