### ISSUE TITLE
Allow iterator input to parser

### ISSUE THREAD

**Issue by MaciejPatro** [p-ranav/argparse#153]
Hello,

There seems to be no option for "subcommand" parsers currently. I would like to propose a new functionality that would make life easier in this regard.

1. Support Iterator based invocation for `ArgumentParser::parse_args` function. The idea here is to allow users to have a single container with parameters and provide easily subrange to different parsers.

That would allow to have a `main_parser` decoding subcommands and specific parsers for each subcommand easily usable with single container eg:

```
my_program info --detailed
my_program start --now
```
could be executed:
```cpp
std::vector<std::string> arguments; // already filled correctly with my_program, ...
main_parser.parse_args(std::begin(arguments), std::begin(arguments) + 2);
if(main_parser->get<std::string>("subcommand") == "info")
{
  info_parse.parse_args(std::next(std::begin(arguments)), std::end(arguments));
}
...
```

I can prepare a pull request for the support of `template<typename InputIt> void parse_args(InputIt first, InputIt second)` if this is something acceptable for you

With kind regards,
Maciej

**Comment by skrobinson** [comment]
This is an interesting idea. Could you provide a full mock usage example that could even be added to `README.md` as part of a merge. The example you've given is a little sparse and I'd like to make sure I'm not reading too much into it.

How would you support `--help` output for the main parser and subparsers?
