### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by netheril96** [p-ranav/argparse#164]
The current stable version does not print the argument name when it is invalid, but the HEAD version does. I think this is an important difference.

I'm current using conan.io to manage my dependencies, and they only have stable versions. Surely I can just copy the `argparse.hpp` from the git HEAD to my own code repo, but I'd like to avoid that if possible.

**Comment by p-ranav** [comment]
Created a [new release](https://github.com/p-ranav/argparse/releases/tag/v2.3). Thanks.
