### ISSUE TITLE
Parser using parent parser shows help message for parent parser instead of own message

### ISSUE THREAD

**Issue by ericonr** [p-ranav/argparse#165]
Hi!

I'm using parent parsers with argparse, but it seems that, when used, the automatic `-h,--help` and `-v,--version` options no longer exist in the "child" parser.

```c
int main(int argc, char *argv[])
{
    argparse::ArgumentParser parent_args("parent");
    parent_args.add_argument("-b").help("board").required().scan<'d', int>();

    argparse::ArgumentParser child("child");
    decode_args.add_parents(parent_args);

    try {
        child.parse_args(argc, argv);
    } catch (const std::runtime_error &err) {
        fprintf(stderr, "argparse error: %s\n", err.what());
        return 1;
    }
}
```

Passing `-b <value>` works just fine, but not `-h` or `-v`, nor their long versions. If I use the parent parser though, everything works.

I get the following error:

```
$ ./parent -h
argparse error: -h: expected 0 argument(s). 1 provided.
```

**Comment by ericonr** [comment]
This has been fixed in version 2.3, I will try to update the version in meson's wrapdb.

Sorry for the noise, and thanks for the project!

**Comment by ericonr** [comment]
~~sorry for the noise again~~

The help message, however, is the wrong one, as is the version number. Reopening with new title.

**Comment by ericonr** [comment]
This can be worked around by initializing the parent parser with `argparse::ArgumentParser parent_args("parent", "1.0", argparse::default_arguments::none);`

Maybe documenting it is a good enough stopgap instead of changing how initialization as a whole works. I can make a PR for the README, in that case.

**Comment by skrobinson** [comment]
Thank you for your report. Let me look into this and get back to you next week.

**Comment by skrobinson** [comment]
Digging into the project history, I'm guessing the expected practice is to disable the parent parser default arguments. But that paragraph did not get copied into the README.

You can see [the Python Docs](https://docs.python.org/3/library/argparse.html#parents) are the source of `ArgumentParser::add_parents()` [documentation](https://github.com/p-ranav/argparse#parent-parsers)

You could adapt the relevant Python paragraph (immediately under the code example) to include in `Parent Parsers`. And we should cite the source of all these
direct quotes.

**Comment by ericonr** [comment]
Thank you for the suggestions! I will take a look and try to come up with a PR :)
