### ISSUE TITLE
Adding to help message

### ISSUE THREAD

**Issue by jimbo1969** [p-ranav/argparse#168]
Is there a way to add program-scope (rather than argument-scope) information to the help message?  

I'd like to add a caveat (e.g. "This broadcasting relay ignores messages from its own IP address to avoid a feedback loop.") to the program's help message.  It seems that the help message is automatically generated.  Something like:
`program.help().str() += "Additional important help message."`

Is such a thing possible?

**Comment by skrobinson** [comment]
The are looking for `ArgumentParser::add_description` and `ArgumentParser::add_epilog`.

Hm, we should add that these to the README.

**Comment by skrobinson** [comment]
@jimbo1969 Did either of these functions help?

**Comment by jimbo1969** [comment]
Indeed.  The epilog was just what I was looking for.  Many thanks!
