### ISSUE TITLE
Require support for GCC 7

### ISSUE THREAD

**Issue by JieRen98** [p-ranav/argparse#179]
Hi,

GCC 7 does not have header charconv, could you add some macro for supporting the earlier compilers?

Best regards,
Jie

**Comment by skrobinson** [comment]
`argparse` is a C++17 project and GCC 7 does not fully support C++17. My preference is to not add complexity to extend support back to older compilers. You could use argparge v2.1 or earlier to avoid the need for the `charconv` header.

Out of curiosity, what platform are you using that does not support GCC > v7 and has a command line interface?

**Comment by ndevenish** [comment]
For me: Intel's DPC++ SYCL compiler. The drivers for the FPGA hardware we are targeting only support Red Hat 7, and the intel toolchain requires an underlying GCC 7.4 to run on that OS.

Still, I expect that using v2.1 should be sufficient for our case.

**Comment by tdakhran** [comment]
I can confirm that `v2.1` builds on
```bash
$ lsb_release -d
Description:	Ubuntu 18.04.6 LTS
$ g++ --version | head -n 1
g++ (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
```

**Comment by weiqishen** [comment]
You can replace the charconv header file with open source implementation such as mscharconv
