### ISSUE TITLE
[feature request] check if arg is path

### ISSUE THREAD

**Issue by danielTobon43** [p-ranav/argparse#188]
Hi @p-ranav, 

Thanks for this wonderful tool for modern C++. I was wondering if the `argparse` library could have a feature for checking a path, for example.

```
argparse::ArgumentParser arg_parser(argv[0]);

arg_parser.add_argument("--output").required().isdirectory().help("output directory");
```

This will check if the provided `--output `argument is a path. What I am doing in my projects is to use Boost for this, but would be wonderful if the `argparse` library provide this feature. Same for example If I define an input argument for an integer that must be positive only.

```
std::string output_dir = arg_parser.get<std::string>("--output");

// check if output-dir is path
 boost::filesystem::path dirPath(output_dir);
 if (not boost::filesystem::exists(dirPath) or not boost::filesystem::is_directory(dirPath)) {
    std::cout << output_dir << std::endl;
    std::exit(-1);
 }
```

**Comment by skrobinson** [comment]
There are as many possible checks as there are programs using `argparse`. The `.action` member function allows `argparse` users to make custom checks and conversions on input values.

The C++17 stdlib has `<filesystem>`.

```cpp
#include <argparse/argparse.hpp>
#include <filesystem>

namespace fs = std::filesystem;

int main(int argc, char *argv[]) {
  argparse::ArgumentParser program("path_checker");

  program.add_argument("--output")
    .action([](const std::string& output_dir) {
      fs::path dirPath = output_dir;
      if (not fs::is_directory(dirPath)) {
        std::cout << output_dir << " is not a directory." << std::endl;
        std::exit(-1);
      }
      return dirPath;
    })
    .required()
    .help("output directory");

  program.parse_args(argc, argv);
  std::cout << "output dir: " << program.get<fs::path>("--output") << std::endl;
  return 0;
}
```

A similar pattern could be used to test that an integer is positive.

**Comment by danielTobon43** [comment]
Wonderful, thanks @skrobinson
