### ISSUE TITLE
Update argparse on vcpkg and create release for the 2.7 version.

### ISSUE THREAD

**Issue by felipegodias** [p-ranav/argparse#190]
Hi, currently the argparse version on vcpkg is the 2.2. Do we have any ETA on publish the latest version (2.6) or a possibly 2.7 there?

**Comment by skrobinson** [comment]
AFAICT, you will want to open an Issue with the `vcpkg` project to have a later `argparse` version included in their ports.

**Comment by felipegodias** [comment]
Hmm got it. But do we have any ETA on the 2.7? There's a few changes that it isn't on the 2.6 such as the support for ClangCL that just came few days ago.

**Comment by p-ranav** [comment]
There are some new PRs have that just been opened. Once these are sorted out, I'll release v2.7 - hoping for end of week.
