### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [p-ranav/argparse#2]
Hello.
At first thank you for the library - it's really easy-to-use and feature-enough complete library.

But I have a suggestion - can you create [Conan](https://conan.io/) package for the library? Even if library is single header-only using system-independent package manager has a lof of advantages. 

One note - wiil be fine if you create release of the library. With it will be easier to create a package.

If you have any questions - just ask here.

**Comment by p-ranav** [comment]
* I've created this conanfile.py for argparse:

```python
from conans import ConanFile

class ArgparseConan(ConanFile):
    name = "argparse"
    version = "1.0"
    exports_sources = "include/argparse.hpp"
    no_copy_source = True

    def package(self):
        self.copy("argparse.hpp")
```

* I've uploaded the conan package to https://bintray.com/p-ranav/argparse
* I've also requested to include this package in https://bintray.com/conan/conan-center

Does this meet your needs? Are there better conan servers I should be uploading to?

**Comment by ZaMaZaN4iK** [comment]
That's exactly what I wanted. Thank you a lot!

**Comment by DrunkenMastah** [comment]
Thank you very much , it would be helpfull if you could write it down on your quick start section on readme .I had to dig to here to find it

**Comment by kobi-ca** [comment]
folks - looking at the conan package uploaded, it says 2.1 but I dont think it is matching 2.1
anyone knows what am I missing here?
