### ISSUE TITLE
Emitted message when overriding `--help`

### ISSUE THREAD

**Issue by suzizecat** [p-ranav/argparse#200]
Hello there !

I have a (rather hacky) usecase where I use argparse to process arguments of commands in an interactive session (made with https://github.com/daniele77/cli ).
One of the issues is that the default `--help` will call `std::exit` which is not what you want in this situation.
You want to display help and exit the _calling function_ (not the whole program). 

Now, I overrode the help parameter, as described in the README, but I also have a positional argument. 
Therefore, the argument parser complains about a missing parameter when I call my function with only the `--help` parameter, which makes sense as `--help` is now an optional argument and doesn't bypass further parsing by exiting the whole program.

Is there a better way to do this, or is it simply not possible as of today ?
My exact code is the following : 
```cpp
argparse::ArgumentParser args("Liberty reader","1.0.0",argparse::default_arguments::none);
// Note default_arguments::none

args.add_argument("path")
	.help("Liberty file path");

// Others arguments ...

args.add_argument("-h", "--help") 
		.action([=](const std::string& s) {
			std::cout << args; // Still display the help, but doesn't quit the program.
		})
		.default_value(false)
		.help("shows help message")
		.implicit_value(true)
		.nargs(0);
args.parse_args(extended_args); // Where extended_args would be {"mysoft","--help"}

if (args.get<bool>("help")) // Properly exit the function if help is requested.
	return;
// Rest of the function
```

**Comment by skrobinson** [comment]
You can add a `.default_value` to a positional argument so `.parse_args` will assign a value if one is omitted by the user.

This ability is hinted at in the README under "Restricting the set of values for an argument". But it should probably be made more explicit in the "Positional Arguments" section.

**Comment by suzizecat** [comment]
Thanks !
Even though I think that it is not perfect that the mandatory argument is therefore not mandatory anymore, even though it is probably possible to work around that too.

Anyway, this is good enough for me, therefore thanks again or all of the work on this lib !
