### ISSUE TITLE
build_tests and build_samples

### ISSUE THREAD

**Issue by nunotexbsd** [p-ranav/argparse#207]
Hello, I'm maintaining FreeBSD [port](https://www.freshports.org/devel/argparse/) and I'm in doubt about improving port by adding TESTS and SAMPLES options to the build.

```
if(ARGPARSE_BUILD_SAMPLES)
  add_subdirectory(samples)
endif()

if(ARGPARSE_BUILD_TESTS)
  add_subdirectory(test)
endif()
```
If SAMPLES are builded, should they be installed?
If TESTS are builded, should they be installed?

Thanks,
Nuno Teixeira

**Comment by nunotexbsd** [comment]
Ok, installation doubt of tests and samples solved.

About adding tests and samples build only options to the port may be of any interest to a advance or developer user?
For example, a user choosed TEST and EXAMPLES build (turned off by default), it could access /tests and /samples source directories for further examination. Does this make sense?

Thanks

**Comment by p-ranav** [comment]
Yeah makes sense. Keeping tests and samples buildable for advanced users or for developers is preferred. By default, they don't need to build.

**Comment by nunotexbsd** [comment]
Thanks for explanation.

Cheers
