### ISSUE TITLE
Mututally exclusive arguments

### ISSUE THREAD

**Issue by Krannich479** [p-ranav/argparse#221]
Hi, 
I could really use mutually exclusive (optional) arguments. I can construct constraints using `parser.get<T>()` and boolean logic but this, plus respective error messages, seems like a syntactic overhead. A built-in solution like
```
parser.add_argument("--filter1");
parser.add_argument("--filter2").mutex("--filter1");
```
would be much appreciated. What do you think? Did I overlook such a mechanism in the docs/issues? 

_(Nice work on a simple and lightweight parser!)_

**Comment by skrobinson** [comment]
This might be possible. I would recommend the Python argparse `ArgumentParser.add_mutually_exclusive_group` syntax rather than attaching directly to `Argument` objects.

For your immediate need, have you tried `.is_used`?

```cpp
  if (parser.is_used("--filter1") && parser.is_used("--filter2")) {
    throw std::runtime_error("filter1 and filter2 are not allowed together");
  }
```

**Comment by Krannich479** [comment]
Thanks a lot for implementing this!
