### ISSUE TITLE
A possible memory corruption of m_used_name in Argument copy

### ISSUE THREAD

**Issue by lingerer** [p-ranav/argparse#226]
A quick code
```
	argparse::ArgumentParser dyna;
	{
		argparse::ArgumentParser test("test", "1.0", argparse::default_arguments::none);
		test.add_argument("--v").default_value(1.1);
		test.parse_args(argc, argv);
		dyna = test;
	}
```
Arguments in m_positional_arguments of dyna will lost the m_used_name string_view value. It should be the local variable destruction make string_view failed. m_prefix_chars is the same.

**Comment by skrobinson** [comment]
I initially agreed, but it looks like the `m_used_name` string_view is viewing one of the strings in `Argument::m_names`. Have you tried instrumenting your example (stdout or a debugger) to check the location of the string and view?

**Comment by lingerer** [comment]
m_used_name is the same m_argment_map's key.
I'm not familar with the implement of string_view, **m_used_name** address is xxxx2458 and **m_names** first address is xxxx2450
My suggestion is add a Argument copy construction to deal with it.
