### ISSUE TITLE
ArgumentParser as a container

### ISSUE THREAD

**Issue by skrobinson** [p-ranav/argparse#227]
Recent Issues (#217, #224) make me think people want container-like access to `ArgumentParser`. I'm considering adding `ArgumentParser::at` to return `Argument` and subparser instances.

```cpp
template <typename T = Argument>
T ArgumentParser::at(const std::string key) {}

auto help_arg = program.at("--help");
auto add_cmd = program.at<ArgumentParser>("add");
```

Thoughts, @p-ranav, @lingerer, @bwpge?

**Comment by bwpge** [comment]
@skrobinson hmm good question... I'm definitely not against having container-like access like you have here.

I think maybe there's an alternate route to go with inheritance and making the members protected. I'm not sure if maybe this would make testing insanely more difficult, but in the spirit of Python's `argparse` this is typically what you'll find recommended when the standard one doesn't meet requirements.

**Comment by p-ranav** [comment]
I'm not a fan of leaking the core of the internal implementation details and would prefer to avoid it. Future versions of `argparse` may favor a different data structure to do something. This has already happened a few times in the past where the data structures have been changed either for performance or for convenience. If we expose the internals, then further changes become either difficult or impossible to make while also keeping backwards compatibility. 

From any research I've done on this, it appears that people create some kind of [BaseCommand](https://github.com/pdm-project/pdm/blob/b32030d5f6ec9d76e14c1f6c32df726ba6aefa8a/src/pdm/cli/commands/base.py#L10) class with a `handle` member function and [define derived classes](https://github.com/pdm-project/pdm/blob/b32030d5f6ec9d76e14c1f6c32df726ba6aefa8a/src/pdm/cli/commands/search.py) that implement this `handle` member function. These `handle` member function accept an `argparse.Namespace` object that provides the context. 

I haven't found any example where a developer directly inherits from `argparse.ArgumentParser`, you can correct me on this.

I'm certainly a fan of `ArgumentParser::at` working for both arguments and parsers. It's an easier change to make and would work fine.

**Comment by lingerer** [comment]
I felt a little bit confuse about it. What's the main difference vs [] in ArgumentParse? [] looks like also provide the reference of Argument.

**Comment by p-ranav** [comment]
With `.at<T>()` you can specify the type and get a reference to not only an Argument but also an ArgumentParser (which happens to be a subcommand).

**Comment by skrobinson** [comment]
@lingerer The difference is that I misread `operator[]` ages ago and thought it was just an alternate syntax for `ArgumentParser::get()`. Your question prompted me to look again. Thank you.

But, the main advantage I see to `.at<T>()` is that operator templates are verbose to use.

```cpp
program.at("--help")
program.at<ArgumentParser>("add")

// versus

program["--help"]
program.operator[]<ArgumentParser>("add")
```

**Comment by lingerer** [comment]
If it  provide more type transform or something for the reference , I think it will be a good way than []
