### ISSUE TITLE
Internal compiler error MSVC 14.16

### ISSUE THREAD

**Issue by c0rn1ie** [p-ranav/argparse#228]
An internal compiler error occurs when compiling the basic `argparse` example in `README.md` with:

* `MSVC v141 - VS 2017 C++ x64/x86 Build Tools (v14.16)`
* Specifying `/std:c++17`

![image](https://user-images.githubusercontent.com/109454050/199967048-1671e28a-ebb9-4f19-a160-a5bc4b987138.png)

https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1001?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(C1001)%26rd%3Dtrue&view=msvc-170

**Comment by skrobinson** [comment]
Thank you for your initial report and screenshot. Please provide a few more details.

Is this pure `MSVC` or `MSVC + Clang-cl`?

Which version of `argparse` are you using?

The MS Learn article you referenced indicates this is "often due to the combination of a particular expression and an optimization option". What optimization options are you using? Does disabling optimizations remove the error?

**Comment by c0rn1ie** [comment]
Pure MSVC.

I'm using `v2.9 of `argparse`.

The build in the screenshot is a `Debug` solution target, so it's not optimized. However, I've attached the detailed build output, including the `cl.exe` invocation:

[mscv_141_compiler_error.txt](https://github.com/p-ranav/argparse/files/9941976/mscv_141_compiler_error.txt)

The project compiles successfully with `MSVC v142 - VS 2019 C++ x64/x86 Build Tools (v14.29)`.

**Comment by lingerer** [comment]
I tried v141 in vs2022， and even including will failed. I suspect it's about v141 under new vs version.

**Comment by c0rn1ie** [comment]
> I tried v141 in vs2022， and even including will failed. I suspect it's about v141 under new vs version.

I'm not sure what you mean. The same error occurs using VS 2017.

**Comment by lingerer** [comment]
VS 2017 seems not fully support c++17

**Comment by skrobinson** [comment]
> I tried v141 in vs2022， and even including will failed.

I think @lingerer means it's the v141 build tools that show the conflict, for any IDE version.

@c0rn1ie Thank you for including the detailed build output. That file points to line 1169 in argparse.hpp as the error source.

I suspect it's the `[[maybe_unused]] attribute`, added in `VS 2017.3` (see https://devblogs.microsoft.com/cppblog/c17-features-in-vs-2017-3/), that is triggering the error.

I don't understand all the MS version numbers and how they mesh, but can you use a later VS 2017 update (or newer build tools version)?

**Comment by c0rn1ie** [comment]
The errors I've reported above apply to the latest VS 2017.

As I mentioned here https://github.com/p-ranav/argparse/issues/228#issuecomment-1304265642, `argparse` compiles with VS 2019 (v142). Please update the `README.md` with the officially supported MSVC version.

**Comment by marzer** [comment]
@c0rn1ie 

> Please update the README.md with the officially supported MSVC version.

Technically speaking they already have; the readme states the library requires C++17, and VS2017 does not advertise a full C++17 implementation.

Per [this article](https://learn.microsoft.com/en-us/cpp/overview/what-s-new-for-cpp-2017?view=msvc-170) it is only about 75% of the way there.

**Comment by c0rn1ie** [comment]
I'm referring to this:

![image](https://user-images.githubusercontent.com/109454050/200532872-592b2e3d-f388-45de-9416-af0ffb8a3d96.png)

**Comment by marzer** [comment]
Ah, yep. Sorry, didn't see that one.
