### ISSUE TITLE
Usage text inconsistent when overriding short flags used by default arguments

### ISSUE THREAD

**Issue by csparker247** [p-ranav/argparse#235]
When using `default_arguments::[none|help|version]` and providing arguments with `-h/-v` short flags, the usage text still prints as if those short flags relate to `--help` and `--version`:
```c++
ArgumentParser program("foo", "1.0", default_arguments::none);
program.add_argument("-h", "--hint");
program.add_argument("-v", "--verbose");
program.add_argument("--bar");
std::cout << program.usage();  // Usage: foo [-h] [--bar VAR]
```

If you remove the short flags, the usage text is correct:
```c++
program.add_argument("--hint");
program.add_argument("--verbose");
program.add_argument("--bar");
std::cout << program.usage();  // Usage: foo [--hint VAR] [--verbose VAR] [--bar VAR]
```

This seems to be caused by specialization of `-h/-v` in `ArgumentParser.usage()` that reasonably didn't anticipate that those short flags could be overriden:
https://github.com/p-ranav/argparse/blob/a8aa3cc999b1318cf99f9ed0de514a6659faa45e/include/argparse/argparse.hpp#L1368-L1372

**Comment by aayush749** [comment]
Hey @csparker247, I've added a fix for this issue. Let me know if this works for you.

**Comment by csparker247** [comment]
Hi @aayush749, this works great! Thanks!

**Comment by p-ranav** [comment]
Merged. Thanks @aayush749
