### ISSUE TITLE
Not supported X86

### ISSUE THREAD

**Issue by Nyx2022** [p-ranav/argparse#237]
i compile it with x86, but i occur errors . so iwaana know how to fix it
![image](https://user-images.githubusercontent.com/51039208/201475529-fe1e0558-23fa-441e-960b-4f982d10d0e2.png)

**Comment by aayush749** [comment]
Did you change the C++ version to C++17 (at least). You can do this from project settings in visual studio.
I can run for x86 perfectly fine.

**Comment by marzer** [comment]
@Nyx2022 

> but also show errors like the picture above

Since all the communication on this repository appears to have been conducted in English, It might help if you posted the errors in English, too.

**Comment by skrobinson** [comment]
@Nyx2022 Can you make a minimal example that fails with the same errors? For example, does the following fail to compile?

```cpp
#include <argparse/argparse.hpp>

int main(int argc, char *argv[]) {
  argparse::ArgumentParser program("program_name");
  program.add_argument("square");
  return 0;
}
``

**Comment by lingerer** [comment]
I'm quite sure is not this project's fault, is about your VS config

**Comment by Nyx2022** [comment]
> Contributor

yes ,i solved it ,thank oyu
