### ISSUE TITLE
Negative integers and floats.

### ISSUE THREAD

**Issue by ajpmaclean** [p-ranav/argparse#24]
Is it possible to input negative integers or floats? From what I can see `-1` or `-1.2e3` are being treated as optional arguments. Maybe `std::is_integral` and `std::is_floating_point` could be used to first test for integrals or floating points before testing for an optional argument.

**Comment by ajpmaclean** [comment]
Maybe a regex like: `[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?` could be used. This will validate integers and floats.

**Comment by p-ranav** [comment]
Pushed some updates to support this, including 4 test cases. Please test and confirm.

**Comment by p-ranav** [comment]
This referenced commit only adds support for negative integers and floats. No support yet for "-1.2e3" E-notation. Still working on that.

**Comment by p-ranav** [comment]
Pushed some updates to support this, including 6 test cases. Please test and confirm.

**Comment by ajpmaclean** [comment]
Tests are passing for me. Wow - argparse is looking really good!
