### ISSUE TITLE
Package availability on conda-forge

### ISSUE THREAD

**Issue by Hind-M** [p-ranav/argparse#240]
Thanks for this great work! I intend to use `argparse` as a requirement in some software, and realized that the package wasn't available on conda-forge. Am I wrong? If not, is there a reason why it's not? I could also do the work if there isn't another way of simple linking...

**Comment by Hind-M** [comment]
So I created a recipe to make the package available on conda-forge and added you as a maintainer (since you're the creator of the package ;) but no duty regarding the actual maintenance work of course :) )

**Comment by p-ranav** [comment]
There's no particular reason why it's not on coda-forge - just that no one's bothered so far. 

Thank you so much for creating the recipe!
