### ISSUE TITLE
No rule to make target install

### ISSUE THREAD

**Issue by JohanMabille** [p-ranav/argparse#241]
When trying ot install the package as explained in the README, I have the following error:

```bash
make: *** No rule to make target 'install'.  Stop.
```

I try to build and install in a conda environment with the following command:

```bash
cmake -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX $SRC_DIR -DCMAKE_INSTALL_LIBDIR=lib
```

The following fails the same way:

```bash
cmake $SRC_DIR
```

I cannot find a reason that would prevent CPack to generate the install command in the Makefile.

**Comment by JohnGalbraith** [comment]
I have this experience too.  I do not know the reason either, but also determined that `v2.9` still works, and that there was a `CMakeLists.txt` update to change the install behavior after that tag.  The commit actually looks fine to me, so I really don't know what is the specific problem.

So a temporary workaround is to revert to v2.9.

**Comment by terroo** [comment]
He did a check on `CMakeLists`, so he needs to enable this argument for `cmake`. The command to generate the `Makefile` should actually be:
`cmake -DARGPARSE_BUILD_SAMPLES=on -DARGPARSE_BUILD_TESTS=on -DARGPARSE_INSTALL=on ..`

**Comment by JohanMabille** [comment]
@terroo thanks!
