### ISSUE TITLE
Positional Arguments with Compound Toggle Arguments

### ISSUE THREAD

**Issue by ajpmaclean** [p-ranav/argparse#25]
I tested this example with the command line:
```cxx
$ ./main 1 -abc 3.14 2.718 2 --files a.txt b.txt c.txt 3
```
and it fails to parse the options.

Keeping the positional arguments together as in:
```cxx
$ ./main 1 2 3 -abc 3.14 2.71 --files a.txt b.txt c.txt
```
works.
This is where I noticed that negative numbers fail to parse. See: [Issue 24](https://github.com/p-ranav/argparse/issues/24)

**Comment by p-ranav** [comment]
Yes, this used to be possible. In an effort to simplify the code base, support for having optional arguments in the middle of a parameter sequence was dropped. I've updated the README to clarify this.

**Comment by ajpmaclean** [comment]
Thanks
