### ISSUE TITLE
Allow argument alias

### ISSUE THREAD

**Issue by HenryRLee** [p-ranav/argparse#26]
I am wondering whether we could add alias for arguments. For example, having `--verbose` as an argument, we can also allow `-v` as an alias.

So in the code, maybe we can do:

```
program.add_argument("--verbose")
  .default_value(false)
  .implicit_value(true)
  .alias("-v");
```

Any advice?

**Comment by p-ranav** [comment]
```add_argument``` takes variadic number of arguments. So, you can just do:

```cpp
program.add_argument("-v", "--verbose")
  .default_value(false)
  .implicit_value(true);
```

**Comment by HenryRLee** [comment]
@p-ranav That's nice to hear. Thank you.
