### ISSUE TITLE
Printing help message

### ISSUE THREAD

**Issue by unins000exe** [p-ranav/argparse#262]
My program uses windows-style ("/"):
* `parser.set_prefix_chars("-/");`
* `parser.set_assign_chars("=:");`

But in this case, when displaying a help message:
![image](https://user-images.githubusercontent.com/61385484/224036474-ff111530-426c-4eaf-8ffe-2cfff64706bd.png)
For some reason, the teams are not exactly under each other.

Why is this happening? What to do?

**Comment by p-ranav** [comment]
Hi. Thanks for the issue. 

Can you paste a reproducible example here so I can investigate?

**Comment by unins000exe** [comment]
It would also be nice if you could suggest how to make the help message output /h instead of -h

**Comment by marzer** [comment]
https://github.com/unins000exe/TPRG/blob/7c3dc2846fe3ce82c50b671a6f8a47108cfe0e97/TPRG_Task_1/TPRG_Task_1/main.cpp#L147-L171

Your `/i` and `/n` arguments have an additional empty string parameter `""`, the others do not. Remove the `""`.

**Comment by unins000exe** [comment]
Oh, I see... 
Thank you
