### ISSUE TITLE
A way to require "optional" arguments to present

### ISSUE THREAD

**Issue by zhihaoy** [p-ranav/argparse#27]
Currently it's very inconvenient to make an option in the form of `-o output` required.  It is not checked if it does not present, if you `get("-o")` you get a logic error, which requires lots of post processing.  There should be a way to declare that this argument must present.  If not presents, exception; if only `-o` presents, status quo (a different exception).

Also, the current situation makes `-o` equivalent to not presenting if there is a `default_value`.  I think it's not a very good interface.  I tried to simulate a "all or nothing" default value with `.implicit_value(x).nargs(1)`, but no luck.

**Comment by wtdcode** [comment]
Same here.

Take gcc as an example.

```
/tmp $ echo "" > 1.c
/tmp $ gcc 1.c -o
gcc.exe: error: missing filename after '-o'
```

**Comment by wtdcode** [comment]
See #30.

Give it a try. :)

**Comment by wtdcode** [comment]
To avoid break changes, I rewrite my PR.

See #33 for details.
