### ISSUE TITLE
Recommended way to parse required input

### ISSUE THREAD

**Issue by hungptit** [p-ranav/argparse#275]
Thank you for an awesome argument parsing library. I follow the document and sample code but I have not figured out how to parse the required inputs without specifying the argument (see the sample command below).

```text
./my_parser file1.txt file2.txt 
```

What do I miss?

**Comment by wanjiadenghuo111** [comment]
亲，来信已经收到！祝你快乐！

**Comment by hungptit** [comment]
I use this pattern to resolve my issue. Is there a better way?


```c++
parser.add_argument("path").required().help("The input file or folder").remaining();
...
parser.parse_args(argc, argv);
params.files = (parser.get<std::vector<std::string>>("path"));
```
