### ISSUE TITLE
compiler complains line 686 when --Wall enabled

### ISSUE THREAD

**Issue by szdytom** [p-ranav/argparse#286]
```
third-party/argparse/argparse.hpp: In function ‘std::ostream& argparse::operator<<(std::ostream&, const Argument&)’:
third-party/argparse/argparse.hpp:686:53: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const std::__cxx11::basic_string<char>::size_type’ {aka ‘const long unsigned int’} [-Wsign-compare]
  686 |     while ((pos = argument.m_help.find('\n', prev)) != std::string::npos) {
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
```

**Comment by Caya91** [comment]
SRC = find.cc 
OBJ = $(SRC:.cc=.o)
TGT = find
DEP = $(SRC:.cc=.d)

$(TGT): $(OBJ)
	g++ -std=c++17 -o $@ $+

%.o: %.c Makefile
	g++ -std=c++17 -Wall -Werror -MMD -c -o $@ $<

clean:
	rm -f $(OBJ) $(TGT) $(DEP)

-include $(DEP)

----
with this Makefile the warning doesn't come up

but if you write it like this, the warning comes up
%.o: %.cc Makefile
	g++ -std=c++17 -Wall -Werror -MMD -c -o $@ $<

**Comment by p-ranav** [comment]
Appears to be fixed after this https://github.com/p-ranav/argparse/pull/292
