### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by SimonEbner** [p-ranav/argparse#3]
Really neat library. Will you add tags for releases in the future?

**Comment by p-ranav** [comment]
I've created a [tagged release](https://github.com/p-ranav/argparse/releases/tag/v1.0) of argparse. I'll make sure to create tags for future releases.

**Comment by egorpugin** [comment]
Hi,

We have now inconsistency in git tags.
Previous were `v{Major}.{Minor}` and current is `{Major}.{Minor}`.
This brokes some of our scripts.

Is it possible to keep existing scheme in long term period?
No matter if it is version with or current one (or new one like 1.8.0 etc.).

**Comment by p-ranav** [comment]
Apologies. I'll stick to ```v{Major}.{Minor}```. I've fixed the [tags](https://github.com/p-ranav/argparse/tags).
