### ISSUE TITLE
Incorrect help message for argparse::nargs_pattern::at_least_one

### ISSUE THREAD

**Issue by ruanformigoni** [p-ranav/argparse#322]
Greetings,

I've noticed that when using something like:

```cpp
      m_parser.add_argument("args")
        .nargs(argparse::nargs_pattern::at_least_one)
        .remaining()
        .required()
        .help("Install an application into the default directory");
```

It generates the help message: 

```
Usage: args [--help] [--version] args

Positional arguments:
  args           Install an application into the default directory [nargs: 0 or more] [required]

Optional arguments:
  -h, --help     shows help message and exits 
  -v, --version  prints version information and exits 
```

Shouldn't it say `nargs: 1 or more` instead of 0?

Thanks!

**Comment by wanjiadenghuo111** [comment]
亲，来信已经收到！祝你快乐！

**Comment by Eng-MohamedHussien** [comment]
Hi @ruanformigoni,
- Using remaining function overrides number of args from [1- any_num_args] to [0 - any_num_args].
![Screenshot from 2024-08-26 18-30-56](https://github.com/user-attachments/assets/17dbb9f0-4f0e-4498-b1d0-494571359415)
- Kindly, close the ticket if you don't have any question.
