### ISSUE TITLE
Arguments following another argument with explicit .choices() will incorrectly inherit the choices

### ISSUE THREAD

**Issue by tlemo** [p-ranav/argparse#370]
```cpp
  args.add_argument("--foo");
  args.add_argument("--bar").choices("a", "b", "c");
```

With the latest version, passing `foo` before `bar` works as expected:

```shell
test --foo=x --bar=a
```

But if `foo` is passed after `bar` it's incorrectly rejected:

```shell
test --bar=a --foo=x

Invalid argument "--foo" - allowed options: {a, b, c}"
```

**Comment by p-ranav** [comment]
This was fixed [here](https://github.com/p-ranav/argparse/issues/307). I'll make a new release soon (long overdue). In the meantime, can you check with the latest commit in the main branch?

**Comment by p-ranav** [comment]
Created a new release: https://github.com/p-ranav/argparse/releases/tag/v3.1

**Comment by mikisch81** [comment]
@p-ranav 
Ok to be more specific the issue happens when I set `--bar` to accept variable length of arguments:
```
  argparse::ArgumentParser args("arg_test");
  args.add_argument("--foo");
  args.add_argument("--bar")
      .nargs(1, 3)
      .choices("a", "b", "c");
```

So if I give all 3 choices it works ok, but if I give 1 or 2, then it fails:
```
> ./arg_test --bar a b c --foo x
>
```

```
> ./arg_test --bar a b --foo x
Invalid argument "--foo" - allowed options: {a, b, c}
Usage: arg_test [--help] [--version] [--foo VAR] [--bar VAR...]

Optional arguments:
  -h, --help     shows help message and exits
  -v, --version  prints version information and exits
  --foo
  --bar          [nargs=1..3]
>
```

**Comment by Eng-MohamedHussien** [comment]
Hi @p-ranav @mikisch81,
Regarding variable length list of arguments:
``` cpp
program.add_argument("--input_files")
  .nargs(1, 3);  // This accepts 1 to 3 arguments.
```
- It's not handled successfully.
- If you checked [this condition](https://github.com/p-ranav/argparse/blob/master/include/argparse/argparse.hpp#L969), you will notice that the tester needs to pass max number of expected arguments.
- Fix needed.

**Comment by Eng-MohamedHussien** [comment]
- I already prepared fix locally but by next weekend I will prepare my pr.
