### ISSUE TITLE
Merged too fast.

### ISSUE THREAD

**Issue by SuperWig** [p-ranav/argparse#5]
I made a mistake.
 $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}>/include)

Should be CMAKE_CURRENT_LIST_DIR not SOURCE_DIR. Literally just fixed it as you merged lol.

**Comment by p-ranav** [comment]
Hah. Merging too fast is definitely an issue. I'll be more careful next time.

**Comment by SuperWig** [comment]
Also I left the version as a placeholder related to https://github.com/p-ranav/argparse/issues/3

Also I don't know how to do the package version on CMake side of things 🤷‍♂️

**Comment by p-ranav** [comment]
If I'm not mistaken, issue #3 is requesting a git tag for the current version and all future releases. I'll set this up sometime tomorrow and update the CMakeLists to reflect the version number of the master branch.

**Comment by SuperWig** [comment]
That's what I meant, for it to reflect the version.
