### ISSUE TITLE
Arguments which start with a dash could be positional arguments

### ISSUE THREAD

**Issue by wtdcode** [p-ranav/argparse#56]
Consider a common pattern: use a dash `-` to represent `stdin` or `stdout`, however, argparse simply considers all arguments which start with a dash as optional arguments. For more information, see [this line](https://github.com/p-ranav/argparse/blob/6ee8de5f4e173dd9267fa62c5d692418a5af7bdd/include/argparse.hpp#L299).

Therefore, I think we can restrict optional arguments to those which

1) start with a dash.
2) and have a character following that dash.

For instance, `-` is a positional argument while `-m` is an optional argument.

**Comment by wtdcode** [comment]
@p-ranav Do you feel it appropriate to apply such changes? If so, I will draft a pull request these days.

**Comment by p-ranav** [comment]
Yes, I agree with this proposal. Thanks!
