### ISSUE TITLE
Printing program version

### ISSUE THREAD

**Issue by ekmecic** [p-ranav/argparse#78]
Python's argparse [has a special action](https://docs.python.org/3/library/argparse.html#action) that prints the program version and exits.

Currently printing the program version with this library can be done, but the presence of required arguments will also cause an error.

Support for printing the program version would be nice to have as it's an expected part of any CLI, akin to the `--help` option.

**Comment by p-ranav** [comment]
You can [print the help message](https://github.com/p-ranav/argparse#printing-help) using a stream, e.g., `std::cout << program`. 

If that doesn't work for you, you can call [`.help()`](https://github.com/p-ranav/argparse/blob/master/include/argparse/argparse.hpp#L911) to format the help message. And although this is marked as deprecated, you can call [`.print_help()`](https://github.com/p-ranav/argparse/blob/master/include/argparse/argparse.hpp#L920) to print the help message and exit.

If none of these options work for you, let me know what you'd rather have. Thanks.

**Comment by ekmecic** [comment]
The specific problem is that `--version` is a special flag, like `--help`. When that flag is received, the program should ignore other flags, print the version, and exit.

I don't think this is possible in argparse currently if there is a required argument defined.
Take the following naive implementation as an example:

```cpp
#include "argparse.hpp"
#define PROGRAM_VERSION "1.0"

int main(int argc, char** argv) {
  argparse::ArgumentParser program("cli-test");

  program.add_argument("-d", "--dir").required();
  program.add_argument("--version")
         .help("Print program version")
         .default_value(false)
         .implicit_value(true);

  try {
    program.parse_args(argc, argv);
  } catch (const std::runtime_error& err) {
    printf("Error found while parsing command line arguments: %s", err.what().c_str())
    return EXIT_FAILURE;
  }

  if (program.get<bool>("--version") == true) {
    printf("Program version %s\n", PROGRAM_VERSION);
    return;
  }
}
```

Calling `./cli-test --version` will output: 

```
Error found while parsing command line arguments: -d: required.
```

Instead of the expected: 
```
Program version 1.0
```
If there's some functionality I'm missing in this library to implement this in my code, please let me know.
If not, I think the solution is carving out special functionality like Python's argparse does, or how the `--help` flag currently works in this library.

Lastly, thank you for writing this library and making it available. It's been very helpful so far and I appreciate the simplicity of it.

**Comment by p-ranav** [comment]
Makes sense. Thanks for the request. 

I've [pushed](https://github.com/p-ranav/argparse/commit/f3e65f69a9d644ddb13b79809110603456b803c1) support for this. 

You can find the [test case here](https://github.com/p-ranav/argparse/blob/f3e65f69a9d644ddb13b79809110603456b803c1/test/test_version.cpp).

Example usage:

* `ArgumentParser` now takes a second argument, the program version. Defaults to `"1.0"`
* You don't need to create the `--version` argument.
* When you provide `--version` or `-v`, the program will print the version information and exit. 

```cpp
#include "argparse.hpp"
#define PROGRAM_VERSION "1.0"

int main(int argc, char** argv) {
  argparse::ArgumentParser program("cli-test", PROGRAM_VERSION);
  program.add_argument("-d", "--dir").required();

  try {
    program.parse_args(argc, argv);
  } catch (const std::runtime_error& err) {
    printf("Error found while parsing command line arguments: %s", err.what().c_str())
    return EXIT_FAILURE;
  }
}
```

I hope this meets your needs. Please confirm and close.

**Comment by ekmecic** [comment]
Looks good to me. Thanks once again.

**Comment by concatime** [comment]
I would like to point out that in the GNU environment, `-v` is for verbosity, not versioning. See http://catb.org/~esr/writings/taoup/html/ch10s05.html. Can I open an issue for this?

**Comment by reuseman** [comment]
Totally agree with @concatime
