### ISSUE TITLE
How to behave like ls?

### ISSUE THREAD

**Issue by samhocevar** [p-ranav/argparse#81]
The GNU `ls` utility allows its flags to be provided anywhere in the commandline, *e.g.*:

    ls -l file1 file2 file3
    ls file1 file2 file3 -l

If I understand correctly, `.remaining();` does not allow that. Is there a workaround for this or another way to do it?

**Comment by p-ranav** [comment]
@samhocevar There's a [new release](https://github.com/p-ranav/argparse/releases/tag/v2.6) of argparse that will support this feature request. Hope this helps.

Regards,

**Comment by samhocevar** [comment]
Thanks for taking the time to let me know. I ended up not using argparse but it seemed pretty clean at the time, so I think I will evaluate it again.
