### ISSUE TITLE
Default Value Returns Bad Any Cast

### ISSUE THREAD

**Issue by xander-io** [p-ranav/argparse#84]
Hello,

Running this with clang on Mac OS, when trying to use the library as such:
```
argparse::ArgumentParser parser{"program"};
parser.add_argument("-t", "--test")
           .help("Blah")
           .default_value("test");

parser.parse_args(arc, argv);
. . .

parser.get<std::string>("-t"); // Bad any_cast
```
It seems that the compiler thinks that `"test"` is of type `const char[5]`.
I tried `parser.get<char*>("-t")` with no luck as well.
My only workaround was to statically cast within the default value `.default_value(static_cast<std::string>("test"))`.
I realize that this default value arg is getting any casted, but maybe the default value should be templated instead?

**Comment by Tridacnid** [comment]
"test" is of type const char[5], so the compiler isn't wrong. Your solution is correct, when extracting via `get<T>`, the T should be the same type that has been stored in the std::any or the cast will fail and throw a std::bad_any_cast exception like you saw.

I'd recommend not using a static_cast and instead construct an object of the type you would like to extract with `get<T>`. So adding your argument would look like:
```
parser.add_argument("-t", "--test")
           .help("Blah")
           .default_value(std::string{"test"});

```

**Comment by p-ranav** [comment]
i too recommend @Tridacnid 's suggestion. `argparse` relies on type deduction and the compiler isn't wrong in your case. Being explicit with the argument type (by using `.default_value(std::string{"test"})`) is the suggested solution.

**Comment by varung2** [comment]
Hi, I am getting a similar issue to this. The program compiles but when I run it, I have a bad cast for the "--threads" and "--num_samples" options. I initially had this code:


    // Performing argument parsing
    argparse::ArgumentParser program("main");

    // Program specific options 
	program.add_argument("-o", "--output")
		.help("Specify name of output render (png).")
		.default_value("render.png");
	program.add_argument("-t", "--threads")
		.help("Number of threads to use for render.")
		.default_value(-1);
	program.add_argument("-nw", "--no_window")
		.help("Disables interactive view window.")
		.default_value(false)
		.implicit_value(true);

	// Render specific options
	program.add_argument("--orth", "--orthographic")
		.help("Use an orthographic projection.")
		.default_value(false)
		.implicit_value(true); //specifies a flag
	program.add_argument("-ns", "--num_samples")
		.help("Sets the average number of samples per pixel.")
		.default_value(-1);
	program.add_argument("-d", "--dim")
		.help("Image dimensions (width x height).")
		.nargs(2)
		.default_value(std::vector<int>{1024, 576})
		.action([](const std::string& val) {return std::stoi(val);});`

And I tried many other changes to fix it. I tried to change the `-1` values (from the failing option) to `int(-1)`, `static_cast<int>(-1)`, and instantiating a variable and dropping that in as a replacement.  Is `-1` not allowed as a default argument?

**Comment by Tridacnid** [comment]
How are you accessing that cmdline param in code? A sample where you use
the threads param would help.

**Comment by varung2** [comment]
Hi Tridacnid,

I fixed the issue by adding an action to parse the string to an int. I
changed my code to something like this (it's an image because code
formating is bad on email):
[image: image.png]
And then I called the parsed option by doing:
[image: image.png]

For now, this is satisfactory for my program. Please let me know if this is
incorrect or if there is a better way to get the arguments.

Thank you for responding. :)
Best,
varung2
