### ISSUE TITLE
Output default value with help text

### ISSUE THREAD

**Issue by PhilippPaetzold** [p-ranav/argparse#88]
Hi @p-ranav,

I think it would be nice, if you could print default values specified by "default_value" method when outputting the help text:
```
    program
        .add_argument("n")
        .help("Number of iterations to be performed")
        .default_value("10");
```
->
```
...
Positional arguments:
n               Number of messages to be sent (default: 10)
```
this would be really useful

Best regards
Philipp

**Comment by rysson** [comment]
Nice idea, optional of course.

**Comment by cekc** [comment]
Hey, I made a PR
https://github.com/p-ranav/argparse/pull/92

I'm not sure if I should include some extra tests/demos.

Under the hood it uses `details::repr` function to get string representation of default argument, which uses to `<<` operator to `std::ostream`. It also works with basic STL-like containers, printing not more than `details::repr_max_container_size` elements (hardcoded to 5).

Basically, it solves the issue, but still, I haven't figured out what to do with long strings as well as those containing newlines and special symbols.

**Comment by p-ranav** [comment]
I've approved the PR but yes, a few tests are required, e.g.,
* default arg that is integral
* default arg that is float
* default arg that is string
* default arg that is vector
* default arg that is bool
* default arg that is optional
