### ISSUE TITLE
Cmake: could not find git for clone of argparse-populate

### ISSUE THREAD

**Issue by addeps3** [p-ranav/argparse#95]
Hi, Im dealing with a piece of software that relies on this git repo for its configuration. 

What is argparse-populate?

**Comment by p-ranav** [comment]
I do not know `argparse-populate` - that is not part of this repo. 

Can you clarify your question or provide additional information?

**Comment by addeps3** [comment]
Hi. It is solved. Git wasnt installed :) 

Thank you.
